databases:
  - name: ratemylandlord
    plan: free
    databaseName: ratemylandlord
    user: testdeploy

services:
  - type: web
    name: ratemylandlord
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testdeploy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
